port: NIMBUS_WS_PORT
services:
  kafka:
    url: NIMBUS_WS_KAFKA_BROKERS
    approach2:
      event_topic: NIMBUS_WS_KAFKA_APPROACH2_EVENTS_TOPIC
      result_topic: NIMBUS_WS_KAFKA_APPROACH2_RESULTS_TOPIC
    approach3:
      event_topic: NIMBUS_WS_KAFKA_APPROACH3_EVENTS_TOPIC
      result_topic: NIMBUS_WS_KAFKA_APPROACH3_RESULTS_TOPIC
  redis:
    url: NIMBUS_WS_REDIS_ADDRESS
    port: NIMBUS_WS_REDIS_PORT
    pubSubMessageChannel: NIMBUS_WS_REDIS_MESSAGE_CHANNEL
